site_name: Besti CTF|Wiki
site_author: CHTXRT
theme: 
  name: material
  features:
  # - announce.dismiss        # 通知关闭
  - content.action.edit       # 编辑操作
  - content.action.view       # 查看操作
  - content.code.annotate     # 代码注释
  - content.code.copy         # 复制代码
  - content.tabs.link         # 标签链接
  - content.tooltips          # 工具提示
  # - header.autohide         # 自动隐藏头部
  # - navigation.expand       # 展开导航
  - navigation.indexes        # 导航索引
  - navigation.instant      # 即时导航
  # - navigation.prune        # 导航修剪
  # - navigation.sections     # 导航节
  - navigation.tabs         # 导航标签
  # - navigation.tabs.sticky  # 固定导航标签
  - navigation.top            # 导航顶部
  - navigation.footer         # 导航底部
  - navigation.tracking       # 导航跟踪
  - search.highlight          # 搜索高亮
  - search.share              # 搜索分享
  - search.suggest            # 搜索建议
  - toc.follow                # 目录跟随
  # - toc.integrate           # 目录整合
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      #primary: grey # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: Switch to dark mode
        
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  
nav:
  - Hello,BestiCTFer: 
    - index.md
    - Misc | 杂项:
      - Misc/index.md
      - 定级标准: Misc/level.md